### ISSUE TITLE
searching a single documentation

### ISSUE THREAD

**Issue by gutierri** [hardpixel/devdocs-desktop#6]
This is something that has in DevDocs web, but in DevDocs-Desktop does not. The GTK default behavior when tab is used is to go to the next button or something clickable.

ref http://devdocs.io/help#search

**Comment by gutierri** [comment]
@jonian  I do not know to what extent it is possible to do this kind of thing in GTK.
![2017-05-13-19--39--26](https://cloud.githubusercontent.com/assets/1111356/26030551/f90caca0-382c-11e7-991e-719de32614f0.png)

**Comment by jonian** [comment]
@gutierri it is not possible with the [gtk search entry](https://developer.gnome.org/gtk3/stable/GtkSearchEntry.html). It will need a custom widget.

I am a little busy now with work related projects but I will try to implement it when I find some time.

**Comment by gutierri** [comment]
@jonian OK!

**Comment by gutierri** [comment]
@jonian Hey have any references to any suggestions to close this out?

**Comment by jonian** [comment]
Hi @gutierri , sorry for the late response.

I do not have any references to any suggestions. I will give this a try soon.

**Comment by Martin1887** [comment]
+1.

This is the most important missing feature I find. Multiple tabs is useful, but this is necessary.

In GTK the keys pressed can be captured, but I don't know if a filter can be set in a search bar as DevDocs web version does. My suggestion to solve this problem is putting a secondary search bar for the language at the left of the primary search bar, if this search bar is not filled the primary searchs in all languages, otherwise it only searchs in the language specified.

I hope this comment were useful.

**Comment by gutierri** [comment]
I think maybe you do not need to be exactly like in mockup, maybe put some pattern like: `python3:filter:term` or `python:terms search`. If you think OK, we can start working on it.

**Comment by jonian** [comment]
This is now implemented. The ui is not the best looking but for now is easiest option.
![devdocs-filter](https://user-images.githubusercontent.com/4119508/48701158-89222a80-ebf6-11e8-8b0f-fc593595418d.gif)
