### ISSUE TITLE
"Enable dark theme" doesn't get saved

### ISSUE THREAD

**Issue by busimus** [hardpixel/devdocs-desktop#7]
I installed the AUR package and found that the _Enable dark theme_ switch stops being respected after pressing _Save_ button in Preferences, so the program resets to the original theme in any case. And the program always starts with the original theme, even when the switch of the dark theme is enabled.

**Comment by jonian** [comment]
Hi, thanks for your report.

This is an issue with [devdocs](https://github.com/Thibaut/devdocs) and not devdocs-desktop.
It has been reported [here](https://github.com/Thibaut/devdocs/issues/613) for Firefox. I added a comment to let the author know that the issue is present in epiphany browser and devdocs-desktop.
